version: "1"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: username/repo:tag
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
